### ISSUE TITLE
author's email not allowed to contain a . before the @

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/schema#3]
I'm experiencing problems with email adresses like e.g.
``b.vanwerkhoven@myorganization.nl``
seems to be due to regular expression pattern not allowing any dots before the ``@`` symbol.

Here is the relevant section of the code: https://github.com/citation-file-format/schema/blob/e801c3660f27c20b96adff80e8fea9919b4d793b/CFF-Core/schema.yaml#L175

And probably also here:
https://github.com/citation-file-format/schema/blob/e801c3660f27c20b96adff80e8fea9919b4d793b/CFF-Core/schema.yaml#L228

I'm willing to make a PR, but will somebody look at it? My [other PR](https://github.com/citation-file-format/schema/pull/2) has not been merged yet... Maybe that was because the build fails, but AFAICT that has nothing to do with the changes I made.

**Comment by sdruskat** [comment]
Hi @jspaaks: Thanks for flagging this! Yes, please write a PR, I'll look at it. Sorry I've sat on the other one (now merged) for so long, I'm swamped ATM.

**Comment by sdruskat** [comment]
Perhaps we should reduce the regex for email for a simple check that the string contains an `@` and then a `.` later on? Not sure if the regex catches all valid cases, and seems to be buggy on top.

**Comment by jspaaks** [comment]
Indeed, regex'es are not ideal for readability.

For the moment, I think I'll just add a ``\.`` to the regex we have now, seems like a minimum effort solution to a problem that we experience right now. I'll see if i can run a bunch of email addresses through https://regex101.com/ to see if we are missing out on something.

Simplifying the check could also be an option, instead of ``A-Za-z0-9\\!\\#\\$\\%\\&\\'\\*\\+\\/\\=\\?\\^\\_\\`\\{\\|\\}\\~\\-``we could do something like 'longest non-whitespace character sequence not containing `@`' or something to that effect.

BTW the regex'es are sometimes single backslash escaped ([doi](https://github.com/citation-file-format/schema/blob/ca222ec7785e0d0d92e8dcfffa572ad599d8f04d/CFF-Core/schema.yaml#L60) for example; with duplicate `\` BTW), sometimes double backslash escaped ([orcid](https://github.com/citation-file-format/schema/blob/ca222ec7785e0d0d92e8dcfffa572ad599d8f04d/CFF-Core/schema.yaml#L222) for example). Not sure how that affects anything but at least something to be aware of.

**Comment by jspaaks** [comment]
I [changed it](https://github.com/citation-file-format/schema/pull/4) to
```yaml
   pattern: ^[\S]+@[\S]+\.[\S]{2,}$
```
which correctly matches
- ``jsparks@hotmail.com``
- ``j.sparks@esciencecenter.nl``
- ``js.js@mail.net``
- ``jezza.sparks@esciencecenter.nl``
- ``jezza@gmail.co.uk``
- all the email addresses from my contacts

correctly doesn't match addresses with leading whitespace characters, like

- `` jezza.sparks@esciencecenter.nl``

but incorrectly matches email addresses starting with a ``.``, like

- ``.jezza@gmail.co.uk`` 

Overall, I can live with this given the much better readability of the regex.

**Comment by sdruskat** [comment]
Yea, that's a lot better. Thanks!
